### ISSUE TITLE
请问这个怎么解决呀

### ISSUE THREAD

**Issue by aaaawc** [luzefeng/mm131-UICollectionView#1]
mm131-UICollectionView-master/Pods/Kanna/Source/CSS.swift:220:46: 'Index' does not have a member named 'advancedBy'

**Comment by luzefeng** [comment]
升级到xcode7 了么？

**Comment by aaaawc** [comment]
是的 最新的

**Comment by luzefeng** [comment]
我下载了zip，又试了一下，发现可以运行啊。。我的xcode版本 Version 7.0.1，advancedBy应该是swift 2才有的接口

**Comment by aaaawc** [comment]
可以了 原来我的是7.0 不好意思哈

**Comment by luzefeng** [comment]
没事，有问题尽管告诉我
