### ISSUE TITLE
xcode update to 7.1 version bugs

### ISSUE THREAD

**Issue by 342261733** [luzefeng/mm131-UICollectionView#3]
"  Include of non-modular header inside framework module 'Kanna.HTMLTree'  "
when I update Xcode to 7.1 version, this bugs happened to me.
I found some solutions, but it doesn't work.

**Comment by luzefeng** [comment]
before using it, update podfile

**Comment by 342261733** [comment]
解决了。多谢

**Comment by luzefeng** [comment]
多多交流，哈哈
